@extends('layouts.app')

@section('content')

    <x-website.header />
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-lg-10">

                <div class="card shadow-lg border-0">
                    <div class="card-header bg-dark text-white text-center">
                        <h4 class="mb-0">Terms & Conditions</h4>
                    </div>

                    <div class="card-body p-4" style="max-height: 600px; overflow-y: auto;">

                        <p>
                            <strong>A.</strong> This document is an electronic record in terms of the Information Technology
                            Act, 2000 and rules thereunder as applicable. This electronic record is generated by a computer
                            system and does not require any physical or digital signatures.
                        </p>

                        <p>
                            <strong>B.</strong> This document is published in accordance with the provisions of Rule 3 (1)
                            of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing
                            the rules, privacy policy and Terms of Use for access or usage of domain name
                            <strong>novelhealthtech.com</strong> (“Website”), including the related mobile site and mobile
                            application (hereinafter referred to as “Platform”).
                        </p>

                        <p>
                            <strong>C.</strong> The Platform is owned by <strong>Novel Healthtech Solutions Pvt. Ltd.</strong>, a company
                            incorporated under the Companies Act, 1956 with its registered office at
                            <strong>D-101, 2nd Floor, Phase V, Udyog Vihar, Sector 19, Gurugram, Haryana 122016</strong>
                            (hereinafter referred to as "Platform Owner", “we”, “us”, “our”).
                        </p>

                        <p>
                            <strong>D.</strong> Your use of the Platform and services and tools are governed by these Terms
                            of Use. By using the Platform, you shall be contracting with the Platform Owner, and these terms
                            constitute a binding obligation. These Terms may be modified at any time without prior notice.
                        </p>

                        <p>
                            <strong>E.</strong> For the purpose of these Terms, “you”, “your” or “user” shall mean any
                            natural or legal person who has agreed to use the Platform.
                        </p>

                        <p class="fw-bold text-danger">
                            F. ACCESSING, BROWSING OR USING THE PLATFORM INDICATES YOUR AGREEMENT TO THESE TERMS OF USE.
                        </p>

                        <hr>

                        <h6 class="fw-bold mb-3">Usage Terms</h6>

                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"><strong>I.</strong> You agree to provide true, accurate and complete
                                information during registration and are responsible for all activities under your account.
                            </li>
                            <li class="list-group-item"><strong>II.</strong> No warranty is provided regarding accuracy,
                                completeness, or suitability of information.</li>
                            <li class="list-group-item"><strong>III.</strong> Use of the Platform and Services is entirely
                                at your own risk.</li>
                            <li class="list-group-item"><strong>IV.</strong> All content including design, layout, graphics
                                is proprietary to Novelhealthtech.</li>
                            <li class="list-group-item"><strong>V.</strong> Unauthorized use may lead to legal action.</li>
                            <li class="list-group-item"><strong>VI.</strong> You agree to pay applicable charges for
                                Services.</li>
                            <li class="list-group-item"><strong>VII.</strong> You shall not use the Platform for any
                                unlawful purpose.</li>
                            <li class="list-group-item"><strong>VIII.</strong> Third-party links are governed by their own
                                policies.</li>
                            <li class="list-group-item"><strong>IX.</strong> Transactions constitute a legally binding
                                contract.</li>
                            <li class="list-group-item"><strong>X.</strong> You agree to indemnify and hold harmless
                                Novelhealthtech from any third-party claims.</li>
                            <li class="list-group-item"><strong>XI.</strong> Liability shall not exceed ₹100 or the amount
                                paid, whichever is lower.</li>
                            <li class="list-group-item"><strong>XII.</strong> Force majeure events exempt liability.</li>
                            <li class="list-group-item"><strong>XIII.</strong> These Terms are governed by the laws of
                                India.</li>
                            <li class="list-group-item"><strong>XIV.</strong> Courts at <strong>Gurugram, Haryana</strong>
                                shall have exclusive jurisdiction.</li>
                            <li class="list-group-item"><strong>XV.</strong> All communications must be sent using contact
                                details available on the Platform.</li>
                        </ul>

                    </div>


                </div>

            </div>
        </div>
    </div>



    <x-website.footer />

@endsection